repo: 'retro-sign'
canvasCourse: '467503'
canvasAssignment: '4202587'

naming: true
commits: 2
liveWebsite: true

html:
  - path: 'index.html'
    locked: true

css:
  - path: 'css/main.css'
    valid: true
    bestPractices: true
    has:
      - ['html', 'box-sizing', 'border-box']
      - ['html', 'text-size-adjust', '100%']
      - ['html', '-moz-text-size-adjust', '100%']
      - ['html', '-ms-text-size-adjust', '100%']
      - ['html', '-webkit-text-size-adjust', '100%']
      - ['*', 'box-sizing', 'inherit']
      - ['body', 'margin', '0']
      - ['.btn', 'cursor', 'pointer']
      - ['.btn:active']
    search:
      - '@-moz-viewport'
      - '@-ms-viewport'
      - '@-o-viewport'
      - '@-webkit-viewport'
      - '@viewport'
      - '\.lines'
      - '\.engage'
      - 'path'
      - '\:nth-child\('
      - '@keyframes'
      - 'stroke-dasharray'
      - 'animation'
      - 'transition'
      - 'transition-delay'

js:
  - path: 'js/main.js'
    valid: true
    bestPractices: true
    search:
      - "\\$\\('svg'\\)"
      - "\\$\\('\\.btn'\\)"
      - "\\.on\\('click'\\, function \\("
      - ['\.(has|toggle|add|remove)Class\(', 'Expected class manipulation']

screenshots:
  - path: 'index.html'
    sizes: [980]

functionality:
  - path: 'index.html'
    tests:
      - |
        let totalEvents = 3;
        let svg = $('svg');
        let oldClassLength = svg.classList.length;
        let btn = $('.btn');
        let btnFill = $('path:nth-child(2)', btn);
        let oldBtnFill = css(btnFill).fill;
        let path = $('.lines path');
        let oldAnimName = css(path).animationName;
        let oldStrokeDasharray = css(path).strokeDasharray;
        let letterE = $('.engage path:first-child');
        let oldLetterEFill = css(letterE).fill;

        var checkPass = function () {
          if (totalEvents <= 0) pass();
        };

        btnFill.addEventListener('transitionend', function () {
          if (oldBtnFill == css(btnFill).fill) fail('The button doesn’t change colour');
          totalEvents--;
          checkPass();
        });

        path.addEventListener('animationend', function () {
          if (oldStrokeDasharray == css(path).strokeDasharray) fail('The `stroke-dasharray` doesn’t change in the animation');
          totalEvents--;
          checkPass();
        });

        letterE.addEventListener('transitionend', function () {
          if (oldLetterEFill == css(letterE).fill) fail('The letters don’t change colour');
          totalEvents--;
          checkPass();
        });

        btn.dispatchEvent(ev('click'));
        if (svg.classList.length <= oldClassLength) fail('The class does’t change on the SVG');
        if (oldAnimName == css(path).animationName) fail('An animation isn’t added to the lines');
